---
on:
  pull_request:

jobs:
  markdownlint:
    uses: Stromweld/github-workflows/.github/workflows/markdown-lint.yml@main

  yamllint:
    uses: Stromweld/github-workflows/.github/workflows/yaml-lint.yml@main

  terraformlint:
    uses: Stromweld/github-workflows/.github/workflows/terraform-lint.yml@main
    secrets: inherit

  terraformplan:
    uses: Stromweld/github-workflows/.github/workflows/terraform-plan.yml@main
    secrets: inherit

  check:
    if: always()
    needs:
      - markdownlint
      - yamllint
      - terraformlint
      - terraformplan
    runs-on: Ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@main
        with:
          allowed-failures:
          allowed-skips:
          jobs: ${{ toJSON(needs) }}
