---
on:
  pull_request:
    paths:
      - '**.md'

jobs:
  markdown-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@main
      - name: Run Markdown Lint
        uses: actionshub/markdownlint@main
